[versions]
biz-aQute-bnd = "6.1.0"
com-squareup-moshi = "1.13.0"
com-squareup-okio = "3.0.0"
info-picocli = "4.6.2"
org-bouncycastle = "1.70"
org-jetbrains-dokka = "1.6.0"
org-jetbrains-kotlin = "1.6.10"
org-junit-jupiter = "5.8.2"

[libraries]
aQute-bnd-gradle = { module = "biz.aQute.bnd:biz.aQute.bnd.gradle", version.ref = "biz-aQute-bnd" }
aQute-resolve = { module = "biz.aQute.bnd:biz.aQute.resolve", version.ref = "biz-aQute-bnd" }
amazon-corretto = "software.amazon.cryptools:AmazonCorrettoCryptoProvider:1.6.1"
android-gradle = "com.android.tools.build:gradle:7.0.4"
animalsniffer-plugin = "ru.vyarus:gradle-animalsniffer-plugin:1.5.4"
assertj-core = "org.assertj:assertj-core:3.21.0"
benmanes-versions = "com.github.ben-manes:gradle-versions-plugin:0.42.0"
bouncycastle-bcpkix = { module = "org.bouncycastle:bcpkix-jdk15to18", version.ref = "org-bouncycastle" }
bouncycastle-bcprov = { module = "org.bouncycastle:bcprov-jdk15to18", version.ref = "org-bouncycastle" }
bouncycastle-bctls = { module = "org.bouncycastle:bctls-jdk15to18", version.ref = "org-bouncycastle" }
brotli-dec = "org.brotli:dec:0.1.2"
animalsniffer-annotations = "org.codehaus.mojo:animal-sniffer-annotations:1.20"
codehaus-signature-java18 = "org.codehaus.mojo.signature:java18:1.0"
conscrypt-openjdk = "org.conscrypt:conscrypt-openjdk-uber:2.5.2"
dokka-all-modules-page-plugin = { module = "org.jetbrains.dokka:all-modules-page-plugin", version.ref = "org-jetbrains-dokka" }
dokka-dokka-base = { module = "org.jetbrains.dokka:dokka-base", version.ref = "org-jetbrains-dokka" }
dokka-dokka-gradle-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "org-jetbrains-dokka" }
dokka-gfm-template-processing-plugin = { module = "org.jetbrains.dokka:gfm-template-processing-plugin", version.ref = "org-jetbrains-dokka" }
dokka-jekyll-template-processing-plugin = { module = "org.jetbrains.dokka:jekyll-template-processing-plugin", version.ref = "org-jetbrains-dokka" }
eclipse-jetty-client = "org.eclipse.jetty:jetty-client:9.4.27.v20200227"
errorprone-gradle-plugin = "net.ltgt.gradle:gradle-errorprone-plugin:2.0.2"
findbugs-jsr305 = "com.google.code.findbugs:jsr305:3.0.2"
graalvm-nativeimage-svm = "org.graalvm.nativeimage:svm:22.0.0.2"
guava-jre = "com.google.guava:guava:31.0.1-jre"
hamcrest-library = "org.hamcrest:hamcrest-library:2.2"
httpcomponents-httpclient5 = "org.apache.httpcomponents.client5:httpclient5:5.0"
info-picocli = { module = "info.picocli:picocli", version.ref = "info-picocli" }
info-picocli-codegen = { module = "info.picocli:picocli-codegen", version.ref = "info-picocli" }
japicmp-gradle-plugin = "me.champeau.gradle:japicmp-gradle-plugin:0.3.0"
jnr-unixsocket = "com.github.jnr:jnr-unixsocket:0.38.15"
johnrengelman-shadow = "gradle.plugin.com.github.johnrengelman:shadow:7.1.0"
jsoup = "org.jsoup:jsoup:1.14.3"
junit = "junit:junit:4.13.2"
junit-jupiter-api = { module = "org.junit.jupiter:junit-jupiter-api", version.ref = "org-junit-jupiter" }
junit-jupiter-engine = { module = "org.junit.jupiter:junit-jupiter-engine", version.ref = "org-junit-jupiter" }
junit-jupiter-params = { module = "org.junit.jupiter:junit-jupiter-params", version.ref = "org-junit-jupiter" }
junit-vintage-engine = "org.junit.vintage:junit-vintage-engine:5.8.2"
kotlin-annotation-processing-gradle = { module = "org.jetbrains.kotlin:kotlin-annotation-processing-gradle", version.ref = "org-jetbrains-kotlin" }
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "org-jetbrains-kotlin" }
kotlin-osgi-bundle = { module = "org.jetbrains.kotlin:kotlin-osgi-bundle", version.ref = "org-jetbrains-kotlin" }
kotlin-scripting-compiler-embeddable = { module = "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable", version.ref = "org-jetbrains-kotlin" }
kotlin-stdlib = { module = "org.jetbrains.kotlin:kotlin-stdlib", version.ref = "org-jetbrains-kotlin" }
kotlin-test-annotations = { module = "org.jetbrains.kotlin:kotlin-test-annotations-common", version.ref = "org-jetbrains-kotlin" }
kotlin-test-common = { module = "org.jetbrains.kotlin:kotlin-test-common", version.ref = "org-jetbrains-kotlin" }
kotlin-test-js = { module = "org.jetbrains.kotlin:kotlin-test-js", version.ref = "org-jetbrains-kotlin" }
kotlin-test-junit = { module = "org.jetbrains.kotlin:kotlin-test-junit", version.ref = "org-jetbrains-kotlin" }
kotlin-test-junit5 = { module = "org.jetbrains.kotlin:kotlin-test-junit5", version.ref = "org-jetbrains-kotlin" }
littlerobots-vcuplugin = "nl.littlerobots.vcu:plugin:0.3.0"
mannodermaus-androidjunit5 = "de.mannodermaus.gradle.plugins:android-junit5:1.8.0.0"
openjsse = "org.openjsse:openjsse:1.1.8"
eclipse-osgi = "org.eclipse.platform:org.eclipse.osgi:3.17.100"
palantir-gradle-graal = "gradle.plugin.com.palantir.graal:gradle-graal:0.10.0"
puppycrawl-checkstyle = "com.puppycrawl.tools:checkstyle:9.2"
robolectric-android = "org.robolectric:android-all:12-robolectric-7732740"
signature-android-apilevel21 = "net.sf.androidscents.signature:android-api-level-21:5.0.1_r2"
spotless-gradle = "com.diffplug.spotless:spotless-plugin-gradle:6.0.4"
squareup-moshi = { module = "com.squareup.moshi:moshi", version.ref = "com-squareup-moshi" }
squareup-moshi-kotlincodegen = { module = "com.squareup.moshi:moshi-kotlin-codegen", version.ref = "com-squareup-moshi" }
squareup-okio = { module = "com.squareup.okio:okio", version.ref = "com-squareup-okio" }
squareup-okio-fakefilesystem = { module = "com.squareup.okio:okio-fakefilesystem", version.ref = "com-squareup-okio" }
vanniktech-publish-plugin = "com.vanniktech:gradle-maven-publish-plugin:0.18.0"
assertk = "com.willowtreeapps.assertk:assertk:0.25"

[plugins]
aQute-bnd = "biz.aQute.bnd:6.1.0"
aQute-bnd-builder = "biz.aQute.bnd.builder:6.1.0"
aQute-bnd-workspace = "biz.aQute.bnd.workspace:6.1.0"
android = "android:7.0.4"
android-application = "com.android.application:7.0.4"
android-asset-pack = "com.android.asset-pack:7.0.4"
android-asset-pack-bundle = "com.android.asset-pack-bundle:7.0.4"
android-base = "com.android.base:7.0.4"
android-dynamic-feature = "com.android.dynamic-feature:7.0.4"
android-internal-application = "com.android.internal.application:7.0.4"
android-internal-asset-pack = "com.android.internal.asset-pack:7.0.4"
android-internal-asset-pack-bundle = "com.android.internal.asset-pack-bundle:7.0.4"
android-internal-dynamic-feature = "com.android.internal.dynamic-feature:7.0.4"
android-internal-library = "com.android.internal.library:7.0.4"
android-internal-reporting = "com.android.internal.reporting:7.0.4"
android-internal-test = "com.android.internal.test:7.0.4"
android-internal-version-check = "com.android.internal.version-check:7.0.4"
android-library = "com.android.library:7.0.4"
android-lint = "com.android.lint:7.0.4"
android-reporting = "com.android.reporting:7.0.4"
android-test = "com.android.test:7.0.4"
animalsniffer = "ru.vyarus.animalsniffer:1.5.4"
de-mannodermaus-android-junit5 = "de.mannodermaus.android-junit5:1.8.0.0"
diffplug-gradle-spotless = "com.diffplug.gradle.spotless:6.0.4"
diffplug-spotless = "com.diffplug.spotless:6.0.4"
github-ben-manes-versions = "com.github.ben-manes.versions:0.42.0"
github-johnrengelman-shadow = "com.github.johnrengelman.shadow:7.1.0"
gradle-japicmp = "me.champeau.gradle.japicmp:0.3.0"
jetbrains-dokka = "org.jetbrains.dokka:1.6.0"
jetbrains-kotlin-android = "org.jetbrains.kotlin.android:1.6.10"
jetbrains-kotlin-android-extensions = "org.jetbrains.kotlin.android.extensions:1.6.10"
jetbrains-kotlin-js = "org.jetbrains.kotlin.js:1.6.10"
jetbrains-kotlin-jvm = "org.jetbrains.kotlin.jvm:1.6.10"
jetbrains-kotlin-kapt = "org.jetbrains.kotlin.kapt:1.6.10"
jetbrains-kotlin-multiplatform = "org.jetbrains.kotlin.multiplatform:1.6.10"
jetbrains-kotlin-multiplatform-pm20 = "org.jetbrains.kotlin.multiplatform.pm20:1.6.10"
jetbrains-kotlin-native-cocoapods = "org.jetbrains.kotlin.native.cocoapods:1.6.10"
jetbrains-kotlin-native-performance = "org.jetbrains.kotlin.native.performance:1.6.10"
jetbrains-kotlin-platform-android = "org.jetbrains.kotlin.platform.android:1.6.10"
jetbrains-kotlin-platform-common = "org.jetbrains.kotlin.platform.common:1.6.10"
jetbrains-kotlin-platform-js = "org.jetbrains.kotlin.platform.js:1.6.10"
jetbrains-kotlin-platform-jvm = "org.jetbrains.kotlin.platform.jvm:1.6.10"
jetbrains-kotlin-plugin-parcelize = "org.jetbrains.kotlin.plugin.parcelize:1.6.10"
jetbrains-kotlin-plugin-scripting = "org.jetbrains.kotlin.plugin.scripting:1.6.10"
kotlin = "kotlin:1.6.10"
kotlin-android = "kotlin-android:1.6.10"
kotlin-android-extensions = "kotlin-android-extensions:1.6.10"
kotlin-dce-js = "kotlin-dce-js:1.6.10"
kotlin-kapt = "kotlin-kapt:1.6.10"
kotlin-multiplatform = "kotlin-multiplatform:1.6.10"
kotlin-native-cocoapods = "kotlin-native-cocoapods:1.6.10"
kotlin-native-performance = "kotlin-native-performance:1.6.10"
kotlin-parcelize = "kotlin-parcelize:1.6.10"
kotlin-platform-android = "kotlin-platform-android:1.6.10"
kotlin-platform-common = "kotlin-platform-common:1.6.10"
kotlin-platform-js = "kotlin-platform-js:1.6.10"
kotlin-platform-jvm = "kotlin-platform-jvm:1.6.10"
kotlin-scripting = "kotlin-scripting:1.6.10"
kotlin2js = "kotlin2js:1.6.10"
littlerobots-version-catalog-update = "nl.littlerobots.version-catalog-update:0.3.0"
ltgt-errorprone = "net.ltgt.errorprone:2.0.2"
palantir-graal = "com.palantir.graal:0.10.0"
vanniktech-maven-publish = "com.vanniktech.maven.publish:0.18.0"
vanniktech-maven-publish-base = "com.vanniktech.maven.publish.base:0.18.0"
